# Generated by Django 4.1.4 on 2022-12-25 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_id_card_alter_student_passport_series'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['fullname']},
        ),
        migrations.AlterModelTable(
            name='student',
            table='student',
        ),
    ]
