# Generated by Django 4.1.4 on 2023-02-23 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_student_date_of_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentExelData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dean_id', models.IntegerField()),
                ('exel_file', models.FileField(upload_to='student_exel_data/')),
            ],
            options={
                'db_table': 'student_exel_data',
                'ordering': ['dean_id'],
            },
        ),
    ]
