# Generated by Django 4.1.4 on 2023-02-23 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_alter_group_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='language',
            field=models.CharField(choices=[['EN', 'EN'], ['UZ', 'UZ'], ['RU', 'RU'], ['KOR', 'KOR']], max_length=10),
        ),
    ]
